# Page settings

baseurl = "https://g-thomson.netlify.com/"
languageCode = "en-us"
title = "Geoffrey Thomson CV"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Geoffrey Thomson CV"
    author = "Theme created by Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Geoffrey Thomson"
        tagline = "Postdoctoral Associate"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: geoffrey.thomson@yale.edu"
        title = "geoffrey.thomson@yale.edu"

        # [[params.contact.list]]
        # class = "website"
        # icon = "fa-globe"
        # url = "//portfoliosite.com"
        # title = "portfoliosite.com"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/g-thomson"
        title = "github.com/g-thomson"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/gojthomson"
        title = "@GojThomson"

    # Education section
    [params.education]
        enable = true
        title = "Education"
        
        [[params.education.list]]
        degree = "PhD in Biology"
        college = "The University of Auckland"
        dates = "2015 - 2019"

        [[params.education.list]]
        degree = "BSc (Hons) in Biology"
        college = "The University of Auckland"
        dates = "2009 - 2013"

        [[params.education.list]]
        degree = "BA in English"
        college = "The University of Auckland"
        dates = "2009 - 2013"

    # Languages section
    # [params.language]
        # enable = true
        # title = "Languages"

        # [[params.language.list]]
        # language = "English"
        # level = "Native"

        # [[params.language.list]]
        # language = "French"
        # level = "Professional"

        # [[params.language.list]]
        # language = "Russian"
        # level = "Professional"

        # Interests section
    [params.interests]
        enable = true
        title = "Interests"
        
        [[params.interests.list]]
        interest = "Plant Science"
        
        [[params.interests.list]]
        interest = "Developmental Biology"
        
        [[params.interests.list]]
        interest = "Genomics"

        [[params.interests.list]]
        interest = "Synthetic Biology"

        [[params.interests.list]]
        interest = "Data Science"
        
        [[params.interests.list]]
        interest = "Science Education"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**I am a Postdoctoral Associate** in the Jacob Lab at Yale University. I am interested in understanding the molecular underpinnings of plant development and how they can be manipulated for beneficial ends. Previously I have recieved a PhD from The University of Auckland looking at photoperiodic flowering *Medicago truncatula*. I also have a BA in English."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Plant Molecular Biology"
        level = "90%"
                
        [[params.skills.list]]
        skill = "R programming"
        level = "90%"

        [[params.skills.list]]
        skill = "RNA-Seq analysis"
        level = "80%"

        [[params.skills.list]]
        skill = "LaTeX"
        level = "70%"
        
 # Publications
    [params.publications]
        enable = true
        icon = "fa-leanpub"
        title = "Publications"
        
        [[params.publications.list]]
        authors = "**Geoffrey Thomson**, James Taylor, Joanna Putterill"
        year = "2019"
        title = "The transcriptomic response to a short day to long day shift in leaves of the reference legume *Medicago truncatula*"
        reference = "***PeerJ*** 7: e6626."
        DOI = "10.7717/peerj.6626"
        url = "https://peerj.com/articles/6626/"
        
        [[params.publications.list]]
        authors = "Mauren Jaudal, Lulu Zhang, Chong Che, Daniel G Hurley, **Geoffrey Thomson**, Jiangqi Wen, Kirankumar S Mysore, Joanna Putterill"
        year = "2016"
        title = "*MtVRN2* is a Polycomb *VRN2* ‐like gene which represses the transition to flowering in the model legume *Medicago truncatula*"
        reference = "***The Plant Journal*** 86: 145-160. "
        DOI = "10.1111/tpj.13156"
        url = "https://onlinelibrary.wiley.com/doi/abs/10.1111/tpj.13156"
        
        [[params.publications.list]]
        authors = "Luke T Dunning, Alice B Dennis, **Geoffrey Thomson**, Brent J Sinclair, Richard D Newcomb, Thomas R Buckley"
        year = "2013"
        title = "Positive selection in glycolysis among Australasian stick insects"
        reference = "***BMC Evolutionary Biology*** 13:215. "
        DOI = "10.1186/1471-2148-13-215"
        url = "https://bmcevolbiol.biomedcentral.com/articles/10.1186/1471-2148-13-215" 

    # Teaching section
    [params.teaching]
      enable = true
      icon = "fa-briefcase"
      title = "Teaching"
      
      [[params.course.list]]
        course = "Intermediate R: Data Manipulation and Visualisation"
        dates = "July 2017"
        audience = "Winter Bootcamp 2017"
        location = "The University of Auckland"
        details = "This three-hour workshop to post-graduate students introduced the 'tidyverse' approach to data science. Targeting individuals who have encountered R but don't know how to take the next step, this workshop equiped participants with the skills to easily ask questions of their data."
        
      [[params.course.list]]
        course = "Tips and Tricks: Academic Documents with LaTeX" 
        dates = "Feb and July 2017"
        audience = "ResBaz and Winter Bootcamp 2017"
        location = "The University of Auckland"
        details = "This course formed a third of a two-hour workshop introducing post-graduate participants to the functionality of LaTeX. I discuss the benefits of using LaTeX for large documents and stratagies for approaching such projects. Chiefly it consists of useful functions in producing academic documents."

    # Experiences section
    # [params.experiences]
        # enable = true
        # icon = "fa-briefcase"
        # title = "Experiences"

        # [[params.jobs.list]]
        # position = "Lead Developer"
        # dates = "2015 - Present"
        # company = "Startup Hubs, San Francisco"
        # details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

    # Projects section
    # [params.projects]
        # enable = true
        # icon = "fa-archive"
        # title = "Projects"
        # intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        # [[params.projects.list]]
        # title = "Hugrid"
        # url = "https://github.com/aerohub/hugrid"
        # tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

    # Awards section
    [params.awards]
        enable = true
        icon = "fa-trophy"
        title = "Awards"
        
        [[params.awards.list]]
        title = "Runner-up - Student Presentations (2018)"
        tagline = "QRW, Plant Satellite, Queenstown, NZ"

        [[params.awards.list]]
        title = "Best Student Presentation (2017)"
        tagline = "Plant Science Central Conference, Palmeston North, NZ"
        
        [[params.awards.list]]
        title = "Student Travel Award (2017)"
        tagline = "Plant Science Central Conference, Palmeston North, NZ"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Geoffrey Thomson"
